### ISSUE TITLE
Testing Horde.UniformQuorumDistribution not behaving as expected. 

### ISSUE THREAD

**Issue by Ivor** [derekkraan/horde#45] opened 2018-12-04 09:49 UTC
Hi Derek. 

I have a cluster setup with libcluster, on my local machine, as such: 

```
    fixed_example: [
      strategy: Cluster.Strategy.Epmd,
      config: [
        hosts: [:"4000@192.168.43.226", :"4001@192.168.43.226", :"4002@192.168.43.226"],
        secret: "myapp_cluster"
      ]
    ]
```

Where `192.168.43.226` is my WIFI ip address.

I have a horde cluster that uses the results of Node.list() to connect to the other nodes. 

This works perfectly fine. I have a process that should only run on one instance of the cluster and I can confirm this works wonderfully. 

If I call `{:ok, members} = Horde.Cluster.members(MyApp.HordeSupervisor)` I get an :ok tuple and three members that each have the `:alive` distinction. 
However, when I turn my wifi off, and the network splits into 3 partitions, then the response from running `{:ok, members} = Horde.Cluster.members(MyApp.HordeSupervisor)` on each node returns an :ok tuple with only one member and it is still alive. 

The problem then is that `Horde.UniformQuorumDistribution` uses the members list to determine the quorum and since the members updated to only include the one node it can see, it thinks that each of the partitions has quorum, instead of rather killing each of them. 

Do you have any idea if this is the expected behaviour. The problem has to be related to the members list updating but I am not sure where to find this and what could be causing this.

**Comment by derekkraan** [comment] 2018-12-04 09:59
Hi Ivor,

Thanks for the bug report.

In a previous version of Horde, members weren't removed from the members array, but marked as `:dead`. Later this changed, with the predictable result that the `UniformQuorumDistribution` no longer works as intended.

So your observations are correct and this is not expected behaviour.

This is actually a trickier question than it seems at first blush. I'm going to let it simmer in the back of my brain for a bit, maybe I'll come up with something good.

In the meantime, a `StaticQuorumDistribution` would solve your problem (ie, that compares the number of nodes in the cluster with a fixed integer, say, 3 [in which case 2 nodes would be mandatory]). I'd be happy to give pointers if you wanted to take a crack at that.

**Comment by derekkraan** [comment] 2018-12-04 10:06
I've created #47 for implementation of `StaticQuorumDistribution`. #46 is also possibly interesting for you.

**Comment by Ivor** [comment] 2018-12-04 10:20
Thanks Derek! 

I am definitely interested in taking a stab at the StaticQuorumDistribution. It makes sense to have a behaviour as you mention in #47 

Could you give me some pointers as to how one would go about this. 
Could one simply add a similar list to "members" from which the `:dead` members are not removed and used that list in the static version? 

For production, we'll be running this with AWS and will read a list of active nodes from there. I am hoping we can create a solution that can handle the quorum based on the nodes returned by the EC2 cluster, so whatever EC2 spins up for us should be taken as the members at that stage. I think we'll be able to find a way to read that somehow. 

Thanks in advance!

**Comment by Ivor** [comment] 2018-12-04 10:38
Quickly looking at `choose_node/2` and `has_quorum?/1` I see that `choose_node` is used to proxy a process to a new node and `has_quorum?` to determine whether the node is part of the main partition or whether its processes should be terminated. 

You are currently passing in the members which will make it slightly complicated to work with alternative ways of determining quorum. I wonder if it would make sense to pass in `state` instead so that each quorum can do with state what it wants to determine these answers. The existing distribution strategies could read members and take it from there, while static could read a number from the state. We could then also configure a `cluster_membership_function` `[MODULE, :action, args]` option that something like an `AWSUniformDistribution` strategy could call to determine cluster membership. 

Does changing those two functions to take the state and get the members from the state, instead of passing in the members, sound like a reasonable change?

**Comment by derekkraan** [comment] 2018-12-04 10:48
The tricky part with this approach (seems to me) is that you would have to have a way to get your own data into the state of `SupervisorImpl`. Another option is to store that information in another GenServer (or ETS table) which you could refer to from the distribution strategy.

For the AWS strategy this would probably be an ETS table for optimal performance. For UniformStaticDistribution I would recommend making it configurable via `config :horde, UniformStaticDistribution, quorum: 3`

**Comment by Ivor** [comment] 2018-12-04 10:49
Ok thanks! 

I think you have given me a good start. I'll get back to you ASAP. 

Thanks for all the help!

**Comment by mgwidmann** [comment] 2019-01-27 02:34
Read this to get a better understanding of what a UniformQuorumDistribution actually does so thank you, the example test really helped. Would like to see once this is in better working order a bit more information in the documentation about why this would be used. I too would like to use it in an EC2 environment within an autoscaling group. It doesn't make much sense to do a static integer gathered via the AWS API since it can scale up or down at any time so you'd want to have it updated automatically when the a node joined/left the cluster.

**Comment by derekkraan** [comment] 2019-02-01 09:00
@mgwidmann, if you can get a list of nodes from EC2 in your autoscaling group, then you can fairly easily build your own distribution strategy that dynamically adjusts quorum based on the number of nodes in your group. This isn't released yet, so you'll have to either wait a couple of weeks or use `master`.

**Comment by derekkraan** [comment] 2019-04-16 06:13
The way we do membership has changed leading up to 0.5.0. Horde will now *never* add or remove a member from the cluster itself. This means that you should manage cluster membership yourself (with something like libcluster) and it also means that the UniformQuorumDistribution should also work the way you are expecting.

**Closed by derekkraan** 2019-04-16 06:13 UTC
Labels: bug
