### ISSUE TITLE
DynamicSupervisor.start_child hangs on infinite timeout

### ISSUE THREAD

**Issue by jonathanhood** [derekkraan/horde#233] opened 2021-06-10 13:31 UTC
I'm seeing in issue right now where a process is hung in the `:waiting` state.
  1. The process is a GenServer running under a horde DynamicSupervisor.
  2. It is trying to spawn _another_ process on a _different_ horde DynamicSupervisor (via `start_child`).
  3. It seems to be hung waiting on an an infinite `GenServer.call` timeout.

We believe this situation started during a deploy of our application - which involves migrating docker containers to a new version of our software one container at a time. This is quite disruptive to horde as processes move around, but I can't find any specific logs that seem relevant.

The process seems to be hung here (we are using horde 0.8.4):
https://github.com/derekkraan/horde/blob/v0.8.4/lib/horde/dynamic_supervisor.ex#L239

The child_spec for the relevant supervisor:

```
    {Horde.DynamicSupervisor,
     [
       name: RelevantDynamicSupervisor,
       strategy: :one_for_one,
       distribution_strategy: Horde.UniformQuorumDistribution,
       members: :auto
     ]}
```

Of particular interest may be this message at the top of the hung processes queue - which seems to imply that its supervisor may have also gone down / been moved in the cluster / etc. Now, this isn't likely from the _same_ supervisor which we are hung waiting on (the hung process is running on a different super than the one we are waiting on) but... still seemed like a relevant tidbit showing that some thrashing of supervisors was going on.

```
iex(<redacted>@<redacted>)5> Process.info(pid, :messages)        
{:messages,
 [
   {:DOWN, #Reference<0.1444392793.1020788738.11109>, :process,
    #PID<50426.4259.0>, :noconnection},
```

The hung process:

```
iex(<redacted>@<redacted>)2> Process.info(pid)
[
  current_function: {:gen, :do_call, 4},
  initial_call: {:proc_lib, :init_p, 5},
  status: :waiting,
  message_queue_len: 41,
  links: [#PID<0.3226.0>],
  dictionary: [
    "$initial_call": {MyGenServer, :init, 1},
    "$ancestors": [RelevantDynamicSupervisor.ProcessesSupervisor,
     RelevantDynamicSupervisor.Supervisor, Application.Supervisor,
     #PID<0.2851.0>]
  ],
  trap_exit: false,
  error_handler: :error_handler,
  priority: :normal,
  group_leader: #PID<0.2850.0>,
  total_heap_size: 3871,
  heap_size: 1598,
  stack_size: 38,
  reductions: 1054,
  garbage_collection: [
    max_heap_size: %{error_logger: true, kill: true, size: 0},
    min_bin_vheap_size: 46422,
    min_heap_size: 233,
    fullsweep_after: 65535,
    minor_gcs: 1
  ],
  suspending: []
]
```

The top of the stack for the hung process. The redacted `:something_interesting` method in the stack trace below basically is a path straight to the horde line of code listed above.

```
iex(<redacted>@<redacted>)3> Process.info(pid, :current_stacktrace)
{:current_stacktrace,
 [
   {:gen, :do_call, 4, [file: 'gen.erl', line: 214]},
   {GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 1021]},
   {MyGenServer, :something_interesting, 1,
    [file: 'lib/super_cool_cool/my_gen_server.ex', line: 62]},

```

**Comment by fmbraga** [comment] 2021-12-28 12:31
I'm having the same problem on a much simpler application. We're on horde 0.8.5.

I changed DynamicSupervisor to include some logging lines:

```elixir
defmodule Horde.DynamicSupervisor do
  def start_child(supervisor, child_spec) do
    child_spec = Supervisor.child_spec(child_spec, [])
    Logger.warn("#{inspect supervisor} #{inspect({:start_child, child_spec})}")
    result = call(supervisor, {:start_child, child_spec})
    Logger.warn("#{inspect result}")
    result
  end
end
```

and did the same on my GenServer:

```
defmodule My.GenServer do
  def child_spec(opts \\ []) do
    id = Keyword.get(opts, :name, __MODULE__)

    %{
      id: id,
      start: {__MODULE__, :start_link, [opts]},
      shutdown: 10_000,
      restart: :transient
    }
  end

  def start_link(opts \\ []) do
    Logger.warning("opts=#{inspect opts}")
    start_options = Keyword.put(opts, :name, via_tuple())
    GenServer.start_link(__MODULE__, %{}, start_options)
    |> case do
      {:ok, _} = ok ->
        ok

      {:error, {:already_started, pid}} ->
        Logger.info("already started at #{inspect(pid)}, returning :ignore")
        :ignore
    end
  end

  @impl true
  def init(state) do
    Logger.warning("init")
    Process.flag(:trap_exit, true)

    {:ok, state, {:continue, :next_action}}
  end

  def via_tuple(), do: via_tuple(__MODULE__)
  def via_tuple(type), do: My.Registry.via_tuple({__MODULE__, type})
end

defmodule My.Registry do
  use Horde.Registry

  def via_tuple(key) when is_tuple(key), do: {:via, Horde.Registry, {__MODULE__, key}}
end

defmodule My.Application do
  @impl true
  def start(_type, _args) do
    topologies = [
      gossip: [
        strategy: Cluster.Strategy.Gossip,
        connect: {__MODULE__, :cluster_connect_node, []},
        list_nodes: {__MODULE__, :cluster_list_nodes, []}
      ]
    ]

    children = [
      {My.Registry, name: My.Registry, keys: :unique, members: :auto},
      {
        Horde.DynamicSupervisor,
        [
          name: My.HordeSupervisor,
          strategy: :one_for_one,
          distribution_strategy: Horde.UniformDistribution,
          max_restarts: 10_000,
          max_seconds: 1,
          members: :auto,
          delta_crdt_options: [sync_interval: 20]
        ]
      },
      {Cluster.Supervisor, [topologies, [name: My.ClusterSupervisor]]},
      %{
        id: My.GenServerStartup,
        restart: :transient,
        start:
          {Task, :start_link,
           [
             fn -> start_genserver(10_000) end
           ]}
      }
    ]

    opts = [strategy: :one_for_one, name: My.Supervisor]
    Supervisor.start_link(children, opts)
  end

  defp start_genserver(sleep \\ 1000) do
    Task.start_link(fn ->
      Process.sleep(sleep)
      Horde.DynamicSupervisor.wait_for_quorum(My.HordeSupervisor, 30_000)
      Horde.DynamicSupervisor.start_child(My.HordeSupervisor, My.GenServer)
    end)
  end

end
```

I can reproduce this behavior everytime by starting two nodes on my dev machine, one a few minutes after the other, and crashing the first one (:init.stop() produces the same result). 

As soon as the first node is down, we get the logs on surviving node:

```
2021-12-28-07:36:13.700 pid=<0.725.0> mfa=Horde.DynamicSupervisor.start_child/2 line=240 [warning] My.HordeSupervisor {:start_child, %{id: My.GenServer, restart: :transient, shutdown: 10000, start: {My.GenServer, :start_link, [[]]}}}
2021-12-28-07:36:19.678 pid=<0.502.0> mfa=Horde.DynamicSupervisorTelemetryPoller.poll/1 line=37 [warning] Exit while fetching metrics from My.HordeSupervisor.
Skip poll action. Reason: {:timeout, {GenServer, :call, [My.HordeSupervisor, :get_telemetry, 5000]}}.

2021-12-28-07:36:29.680 pid=<0.502.0> mfa=Horde.DynamicSupervisorTelemetryPoller.poll/1 line=37 [warning] Exit while fetching metrics from My.HordeSupervisor.
Skip poll action. Reason: {:timeout, {GenServer, :call, [My.HordeSupervisor, :get_telemetry, 5000]}}.

```

I was able to extract some data from it

```
iex(phoenix_03@127.0.0.1)1>  names = Process.list |> Enum.map(& { &1, Process.info(&1, [:registered_name]) |> Enum.into(%{}) }) |> Enum.into(%{}) |> Enum.filter(fn {_,v} -> is_atom(v[:registered_name]) and Atom.to_string(v[:registered_name]) |> String.match?(~r/(Horde|Registry|My)/) end)  |> Enum.sort(fn {_, v1}, {_, v2} -> v1.registered_name < v2.registered_name end)
[
  {#PID<0.179.0>, %{registered_name: Hex.Registry.Server}},
  {#PID<0.503.0>, %{registered_name: My.ClusterSupervisor}},
  {#PID<0.499.0>, %{registered_name: My.HordeSupervisor}},
  {#PID<0.498.0>, %{registered_name: My.HordeSupervisor.Crdt}},
  {#PID<0.500.0>, %{registered_name: My.HordeSupervisor.ProcessesSupervisor}},
  {#PID<0.496.0>, %{registered_name: My.HordeSupervisor.Supervisor}},
  {#PID<0.495.0>, %{registered_name: My.Registry}},
  {#PID<0.494.0>, %{registered_name: My.Registry.Crdt}},
  {#PID<0.493.0>, %{registered_name: My.Registry.NodeListener}},
  {#PID<0.492.0>, %{registered_name: My.Registry.Supervisor}},
  {#PID<0.485.0>, %{registered_name: My.Supervisor}}
]
iex(phoenix_03@127.0.0.1)2> pid(0,499,0) |> Process.info()
[
  registered_name: Rtmd.HordeSupervisor,
  current_function: {:gen, :do_call, 4},
  initial_call: {:proc_lib, :init_p, 5},
  status: :waiting,
  message_queue_len: 24,
  links: [#PID<0.496.0>],
  dictionary: [
    rand_seed: {%{
       bits: 58,
       jump: #Function<3.92093067/1 in :rand."-fun.exsplus_jump/1-">,
       next: #Function<0.92093067/1 in :rand."-fun.exsss_next/1-">,
       type: :exsss,
       uniform: #Function<1.92093067/1 in :rand."-fun.exsss_uniform/1-">,
       uniform_n: #Function<2.92093067/2 in :rand."-fun.exsss_uniform/2-">
     }, [24059410157520257 | 221324966104329067]},
    "$initial_call": {Horde.DynamicSupervisorImpl, :init, 1},
    "$ancestors": [My.HordeSupervisor.Supervisor, My.Supervisor,
     #PID<0.484.0>]
  ],
  trap_exit: true,
  error_handler: :error_handler,
  priority: :normal,
  group_leader: #PID<0.483.0>,
  total_heap_size: 15175,
  heap_size: 4185,
  stack_size: 44,
  reductions: 103859,
  garbage_collection: [
    max_heap_size: %{error_logger: true, kill: true, size: 0},
    min_bin_vheap_size: 46422,
    min_heap_size: 233,
    fullsweep_after: 65535,
    minor_gcs: 49
  ],
  suspending: []
]
iex(phoenix_03@127.0.0.1)3> pid(0,499,0) |> :sys.get_state
** (exit) exited in: :sys.get_state(#PID<0.499.0>)
    ** (EXIT) time out
    (stdlib 3.15.2) sys.erl:338: :sys.send_system_msg/2
    (stdlib 3.15.2) sys.erl:139: :sys.get_state/1
iex(phoenix_03@10.1.82.96)3>
```

Interestingly enough, I can see another process was started on the surviving node (when it shouldn't: :restart is :temporary):

```
2021-12-28-07:36:13.699 pid=<0.500.0> mfa=My.GenServer.WebSocket.One.start_link/1 line=47 [info] One :one_ws_public websocket started #PID<0.711.0>
```

But that wasn't logged by Horde.DynamicSupervisor.start_child/2. It was started by My.HordeSupervisor.ProcessesSupervisor #PID<0.500.0>. It was running on the crashed node, and was started using Horde.DynamicSupervisor. 

```
defmodule My.GenServer.WebSocket.One
  def ensure_ws_is_running(type) when type in [:one_ws_public] do
    case lookup(type) do
      [] ->
        Horde.DynamicSupervisor.start_child(
          My.HordeSupervisor,
          child_spec(%{type: type})
        )
        |> case do
          {:ok, _} = ok ->
            ok

          {:error, {:already_started, pid}} ->
            {:ok, pid}

          {:error, _} = error ->
            Logger.error("UNKNOWN start_link #{inspect(error)}")
            error

          _ = unknown ->
            Logger.error("UNKNOWN start_link pid: #{inspect(unknown)}")
        end

      pid ->
        {:ok, pid}
    end

  def lookup(type),
      do: Horde.Registry.lookup(My.Registry, name(type))

  defp upcaseFirst(name) when is_atom(name), do: upcaseFirst(Atom.to_string(name))
  defp upcaseFirst(<<first::utf8, rest::binary>>), do: String.upcase(<<first::utf8>>) <> rest
  defp name(type), do: "#{__MODULE__}.#{upcaseFirst(type)}"

  def child_spec(%{type: type}) do
    %{
      id: name(type),
      start: {__MODULE__, :start_link, [%{type: type}]},
      shutdown: 10_000,
      restart: :temporary
    }
  end

end
```

As i observed this, I decided to look at ProcessesSupervisor (after some time):

```
iex(phoenix_03@127.0.0.1)6> pid(0,500,0) |> Process.info()
[
  registered_name: My.HordeSupervisor.ProcessesSupervisor,
  current_function: {:proc_lib, :sync_start_link, 2},
  initial_call: {:proc_lib, :init_p, 5},
  status: :waiting,
  message_queue_len: 2,
  links: [#PID<0.711.0>, #PID<0.725.0>, #PID<0.495.0>],
  dictionary: [
    "$initial_call": {:supervisor, Supervisor.Default, 1},
    "$ancestors": [My.HordeSupervisor.Supervisor, My.Supervisor,
     #PID<0.484.0>]
  ],
  trap_exit: true,
  error_handler: :error_handler,
  priority: :normal,
  group_leader: #PID<0.483.0>,
  total_heap_size: 1978,
  heap_size: 1598,
  stack_size: 32,
  reductions: 9999,
  garbage_collection: [
    max_heap_size: %{error_logger: true, kill: true, size: 0},
    min_bin_vheap_size: 46422,
    min_heap_size: 233,
    fullsweep_after: 65535,
    minor_gcs: 6
  ],
  suspending: []
]
```

It's waiting on :proc_lib.sync_start_link, with timeout: :infinity. Since it is deep into Erlang :gen_server, I now believe my code is flawed. But I can't figure out where.

Can you help me out ?

**Comment by fmbraga** [comment] 2022-01-17 12:44
Hey guys,

I found out my bug. It turns out there was a deadlock condition on `init`.

I must emphasize [the importance of `handle_continue/2`](https://github.com/derekkraan/horde/issues/211#issuecomment-704985757)

Thanks all,

**Comment by derekkraan** [comment] 2022-01-24 10:59
I believe this bug report is indeed a result of user code @jonathanhood. Closing for now but feel free to re-open if you have new insights (or even better: a test that illustrates your problem).

**Closed by derekkraan** 2022-01-24 10:59 UTC
