### ISSUE TITLE
Horde.Cluster.set_members behaving differently for registries and supervisors

### ISSUE THREAD

**Issue by frekw** [derekkraan/horde#90] opened 2019-04-10 12:14 UTC
Please see: https://asciinema.org/a/AKOZTh1jvI1NTa1KK2XMEIBT1

The test app I'm running can be found here: https://github.com/frekw/horde-test

For `Horde.Registry` the member list seem to be replicated (as expected) but for the supervisor it's not.

I could very well be doing something wrong as well but at least I don't _think_ I am.

**Comment by derekkraan** [comment] 2019-04-11 14:37
Thanks for testing & for the bug report. I can reproduce it with 0.5.0-rc.11, but when I try with the branch `react_to_membership_changes`, everything works as expected.

It took me a long time to figure out what was happening here. But now I know what it was. It's a bug in delta_crdt. Basically, if the first delta wasn't propagated within 10s, it would be garbage collected, and the other nodes would be none the wiser. This is now fixed in the current branch I'm working on (which uses a heavily overhauled delta_crdt). #92

**Comment by derekkraan** [comment] 2019-04-11 14:37
Here's a test that reproduces the issue (which I won't be adding to the repo since it takes longer than 10s to run):

```elixir
test "cluster membership is propagated" do                                    
  {:ok, _} = Horde.Supervisor.start_link(name: :prop1, strategy: :one_for_one)
  {:ok, _} = Horde.Supervisor.start_link(name: :prop2, strategy: :one_for_one)
  Process.sleep(11000)                                                        
                                                                              
  :ok = Horde.Cluster.set_members(:prop1, [:prop1, :prop2])                   
  Process.sleep(1000)                                                         
  {:ok, members} = Horde.Cluster.members(:prop1)                              
  assert 2 = Enum.count(members)                                              
  {:ok, members} = Horde.Cluster.members(:prop2)                              
  assert 2 = Enum.count(members)                                              
end                                                                           
```

**Closed by derekkraan** 2019-04-11 14:37 UTC

**Comment by frekw** [comment] 2019-04-11 15:30
Cool! Happy to help :)
