### ISSUE TITLE
Inconsistent behaviour on netsplit recovery for registered, supervised processes.

### ISSUE THREAD

**Issue by bernardd** [derekkraan/horde#186] opened 2019-11-29 02:52 UTC
Having a process that is both registered (with `Horde.Registry`) and supervised (with `Horde.DynamicSupervisor`), then creating and healing a netsplit is causing me some weird results. (It's probably also relevant that I'm running an auto-cluster-membership process, much like the one over in #184).

Depending on the whims of timing, I get either:
* Everything working perfectly
* The DynamicSupervisor process crashing
* The process being lost entirely from both the supervisor and registry

The test code is at the bottom of this post.

The crashes generally take this form:

```
13:10:12.637 [error] GenServer TestSup terminating
** (MatchError) no match of right hand side value: {{:error, {:already_started, #PID<18743.240.0>}}, %Horde.DynamicSupervisorImpl{distribution_strategy: Horde.UniformDistribution, local_process_count: 0, members: %{{TestSup, :"loner-cluster1@127.0.0.1"} => 1, {TestSup, :"loner-cluster3@127.0.0.1"} => 1, {TestSup, :"manager@127.0.0.1"} => 1}, members_info: %{{TestSup, :"loner-cluster1@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster1@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster2@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster2@127.0.0.1"}, status: :dead}, {TestSup, :"loner-cluster3@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster3@127.0.0.1"}, status: :dead}, {TestSup, :"manager@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"manager@127.0.0.1"}, status: :uninitialized}}, name: TestSup, name_to_supervisor_ref: %{{TestSup, :"loner-cluster1@127.0.0.1"} => #Reference<18689.771311882.68681729.104346>, {TestSup, :"loner-cluster2@127.0.0.1"} => #Reference<18689.771311882.68681729.104370>}, process_pid_to_id: %{#PID<18743.240.0> => 160250865716161310950587155304892883039}, processes_by_id: %{160250865716161310950587155304892883039 => {{TestSup, :"loner-cluster3@127.0.0.1"}, %{id: 160250865716161310950587155304892883039, restart: :transient, start: {TestServer, :start_link, [[]]}}, #PID<18743.240.0>}}, shutting_down: false, supervisor_options: [name: TestSup, root_name: TestSup, init_module: Supervisor.Default, strategy: :one_for_one, intensity: 3, period: 5, max_children: :infinity, extra_arguments: [], strategy: :one_for_one, distribution_strategy: Horde.UniformDistribution, process_redistribution: :passive, members: [TestSup]], supervisor_ref_to_name: %{#Reference<18689.771311882.68681729.104346> => {TestSup, :"loner-cluster1@127.0.0.1"}, #Reference<18689.771311882.68681729.104370> => {TestSup, :"loner-cluster2@127.0.0.1"}}, waiting_for_quorum: []}}
    lib/horde/dynamic_supervisor_impl.ex:405: anonymous fn/3 in Horde.DynamicSupervisorImpl.handoff_processes/1
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/horde/dynamic_supervisor_impl.ex:369: Horde.DynamicSupervisorImpl.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:crdt_update, [{:add, {:member_node_info, {TestSup, :"loner-cluster2@127.0.0.1"}}, %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster2@127.0.0.1"}, status: :dead}}, {:add, {:process, 160250865716161310950587155304892883039}, {{TestSup, :"loner-cluster3@127.0.0.1"}, %{id: 160250865716161310950587155304892883039, restart: :transient, start: {TestServer, :start_link, [[]]}}, #PID<18743.240.0>}}, {:remove, {:member, {TestSup, :"loner-cluster2@127.0.0.1"}}}]}
State: %Horde.DynamicSupervisorImpl{distribution_strategy: Horde.UniformDistribution, local_process_count: 0, members: %{{TestSup, :"loner-cluster1@127.0.0.1"} => 1, {TestSup, :"loner-cluster2@127.0.0.1"} => 1, {TestSup, :"loner-cluster3@127.0.0.1"} => 1, {TestSup, :"manager@127.0.0.1"} => 1}, members_info: %{{TestSup, :"loner-cluster1@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster1@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster2@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster2@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster3@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster3@127.0.0.1"}, status: :dead}, {TestSup, :"manager@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"manager@127.0.0.1"}, status: :uninitialized}}, name: TestSup, name_to_supervisor_ref: %{{TestSup, :"loner-cluster1@127.0.0.1"} => #Reference<18689.771311882.68681729.104346>, {TestSup, :"loner-cluster2@127.0.0.1"} => #Reference<18689.771311882.68681729.104370>}, process_pid_to_id: %{#PID<18741.234.0> => 160250865716161310950587155304892883039}, processes_by_id: %{160250865716161310950587155304892883039 => {{TestSup, :"loner-cluster2@127.0.0.1"}, %{id: 160250865716161310950587155304892883039, restart: :transient, start: {TestServer, :start_link, [[]]}}, #PID<18741.234.0>}}, shutting_down: false, supervisor_options: [name: TestSup, root_name: TestSup, init_module: Supervisor.Default, strategy: :one_for_one, intensity: 3, period: 5, max_children: :infinity, extra_arguments: [], strategy: :one_for_one, distribution_strategy: Horde.UniformDistribution, process_redistribution: :passive, members: [TestSup]], supervisor_ref_to_name: %{#Reference<18689.771311882.68681729.104346> => {TestSup, :"loner-cluster1@127.0.0.1"}, #Reference<18689.771311882.68681729.104370> => {TestSup, :"loner-cluster2@127.0.0.1"}}, waiting_for_quorum: []}
```

On other runs (though more rarely), after the netsplit heals, the process just disappears entirely from both the registry and supervisor (this test output shows how the code below catches that - I've done more detailed tests which show that there is indeed no instance of the process left running, registered or otherwise):

```
  1) test test (HordeTest)
     test/horde_test.exs:4
     Expected truthy, got false
     code: assert Enum.all?(pids, &is_pid/1)
     arguments:

         # 1
         [:undefined, :undefined, :undefined, :undefined]

         # 2
         &:erlang.is_pid/1

     stacktrace:
       test/horde_test.exs:30: (test)
```

There's a lot of moving parts here - the supervisor trying to reconcile two supervision trees, the registry trying to remove the duplicate process, and the node monitor trying to merge the cluster back together (and doing it on 4 nodes at once just to make things even more complicated). If there's further or specific testing you'd like me to do, please let me know - I'm going to keep tinkering but right now I'm at a bit of a loose end as to where to even look.

I've included the full test file below - you should just be able to drop it into `horde/test/` and run it with `mix test test/horde_test.exs`.

```elixir
defmodule HordeTest do
  use ExUnit.Case

  test "test" do
    nodes = LocalCluster.start_nodes("loner-cluster", 4, files: [__ENV__.file])

    [n1, n2, n3, n4] = nodes

    Enum.each(nodes, &Node.spawn(&1, __MODULE__, :setup_horde, []))

    Process.sleep(1000)

    {:ok, _pid} = :rpc.call(n1, Horde.DynamicSupervisor, :start_child, [TestSup, TestServer])

    Process.sleep(1000)

    g1 = [n1, n2]
    g2 = [n3, n4]
    Schism.partition(g1)
    Schism.partition(g2)

    Process.sleep(1000)

    Schism.heal(nodes)

    Process.sleep(1000)

    pids = :rpc.multicall(nodes, Horde.Registry, :whereis_name, [{TestRegistry, TestServer}]) |> elem(0)

    assert Enum.all?(pids, &is_pid/1)
    assert pids |> Enum.uniq() |> length == 1
  end

  def setup_horde do
    {:ok, _} = Application.ensure_all_started(:horde)
    {:ok, _} = Horde.Registry.start_link(name: TestRegistry, keys: :unique, delta_crdt_options: [sync_interval: 50])
    {:ok, _} = Horde.DynamicSupervisor.start_link(name: TestSup, strategy: :one_for_one, delta_crdt_options: [sync_interval: 50])
    {:ok, _} = NodeMonitor.start_link([])

    receive do
    end
  end
end

defmodule TestServer do
  use GenServer, restart: :transient

  def start_link(args) do
    GenServer.start_link(__MODULE__, args, name: {:via, Horde.Registry, {TestRegistry, __MODULE__}})
  end

  def init(_) do
    Process.flag(:trap_exit, true)
    {:ok, nil}
  end

  def handle_info({:EXIT, _, {:name_conflict, _, _, _}}, state) do
    {:stop, :normal, state}
  end
end

defmodule NodeMonitor do
  use GenServer

  alias Horde.Cluster

  def start_link(init_arg) do
    GenServer.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  def init(_) do
    :ok = :net_kernel.monitor_nodes(true)
    update_nodes()
    {:ok, nil}
  end

  def handle_info({:nodeup, _node}, s) do
    update_nodes()
    {:noreply, s}
  end

  def handle_info({:nodedown, _node}, s) do
    update_nodes()
    {:noreply, s}
  end

  defp update_nodes do
    nodes = Node.list([:visible, :this])

    registries = for n <- nodes, do: {TestRegistry, n}
    :ok = Cluster.set_members(TestRegistry, registries)

    supervisors = for n <- nodes, do: {TestSup, n}
    :ok = Cluster.set_members(TestSup, supervisors)
  end
end
```

**Comment by bernardd** [comment] 2019-11-29 03:43
In an effort to limit the number of moving parts, I ran some tests with just manual cluster management (code at the bottom of this post). I still fairly consistently saw the crash above, however I didn't see exactly the same "missing process" issue. What I *did* manage to cause, however, was a slightly different supervisor crash:

```
14:37:02.065 [error] GenServer TestSup terminating
** (MatchError) no match of right hand side value: {{:error, {:name_conflict, {TestServer, nil}, TestRegistry, #PID<18570.256.0>}}, %Horde.DynamicSupervisorImpl{distribution_strategy: Horde.UniformDistribution, local_process_count: 0, members: %{{TestSup, :"loner-cluster1@127.0.0.1"} => 1, {TestSup, :"loner-cluster2@127.0.0.1"} => 1, {TestSup, :"loner-cluster3@127.0.0.1"} => 1, {TestSup, :"loner-cluster4@127.0.0.1"} => 1}, members_info: %{{TestSup, :"loner-cluster1@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster1@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster2@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster2@127.0.0.1"}, status: :dead}, {TestSup, :"loner-cluster3@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster3@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster4@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster4@127.0.0.1"}, status: :alive}}, name: TestSup, name_to_supervisor_ref: %{{TestSup, :"loner-cluster1@127.0.0.1"} => #Reference<18568.3730536476.3303276548.200472>, {TestSup, :"loner-cluster2@127.0.0.1"} => #Reference<18568.3730536476.3303276547.200882>, {TestSup, :"loner-cluster3@127.0.0.1"} => #Reference<18568.3730536476.3303276547.200835>, {TestSup, :"loner-cluster4@127.0.0.1"} => #Reference<18568.3730536476.3303276547.200846>}, process_pid_to_id: %{#PID<18566.248.0> => 291013969424479108195919381772622850864}, processes_by_id: %{291013969424479108195919381772622850864 => {{TestSup, :"loner-cluster2@127.0.0.1"}, %{id: 291013969424479108195919381772622850864, restart: :transient, start: {TestServer, :start_link, [[]]}}, #PID<18566.248.0>}}, shutting_down: false, supervisor_options: [name: TestSup, root_name: TestSup, init_module: Supervisor.Default, strategy: :one_for_one, intensity: 3, period: 5, max_children: :infinity, extra_arguments: [], strategy: :one_for_one, distribution_strategy: Horde.UniformDistribution, process_redistribution: :passive, members: [TestSup]], supervisor_ref_to_name: %{#Reference<18568.3730536476.3303276547.200835> => {TestSup, :"loner-cluster3@127.0.0.1"}, #Reference<18568.3730536476.3303276547.200846> => {TestSup, :"loner-cluster4@127.0.0.1"}, #Reference<18568.3730536476.3303276547.200882> => {TestSup, :"loner-cluster2@127.0.0.1"}, #Reference<18568.3730536476.3303276548.200472> => {TestSup, :"loner-cluster1@127.0.0.1"}}, waiting_for_quorum: []}}
    (horde) lib/horde/dynamic_supervisor_impl.ex:405: anonymous fn/3 in Horde.DynamicSupervisorImpl.handoff_processes/1
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (horde) lib/horde/dynamic_supervisor_impl.ex:369: Horde.DynamicSupervisorImpl.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:crdt_update, [{:add, {:member_node_info, {TestSup, :"loner-cluster2@127.0.0.1"}}, %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster2@127.0.0.1"}, status: :dead}}]}
State: %Horde.DynamicSupervisorImpl{distribution_strategy: Horde.UniformDistribution, local_process_count: 0, members: %{{TestSup, :"loner-cluster1@127.0.0.1"} => 1, {TestSup, :"loner-cluster2@127.0.0.1"} => 1, {TestSup, :"loner-cluster3@127.0.0.1"} => 1, {TestSup, :"loner-cluster4@127.0.0.1"} => 1}, members_info: %{{TestSup, :"loner-cluster1@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster1@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster2@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster2@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster3@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster3@127.0.0.1"}, status: :alive}, {TestSup, :"loner-cluster4@127.0.0.1"} => %Horde.DynamicSupervisor.Member{name: {TestSup, :"loner-cluster4@127.0.0.1"}, status: :alive}}, name: TestSup, name_to_supervisor_ref: %{{TestSup, :"loner-cluster1@127.0.0.1"} => #Reference<18568.3730536476.3303276548.200472>, {TestSup, :"loner-cluster2@127.0.0.1"} => #Reference<18568.3730536476.3303276547.200882>, {TestSup, :"loner-cluster3@127.0.0.1"} => #Reference<18568.3730536476.3303276547.200835>, {TestSup, :"loner-cluster4@127.0.0.1"} => #Reference<18568.3730536476.3303276547.200846>}, process_pid_to_id: %{#PID<18566.248.0> => 291013969424479108195919381772622850864}, processes_by_id: %{291013969424479108195919381772622850864 => {{TestSup, :"loner-cluster2@127.0.0.1"}, %{id: 291013969424479108195919381772622850864, restart: :transient, start: {TestServer, :start_link, [[]]}}, #PID<18566.248.0>}}, shutting_down: false, supervisor_options: [name: TestSup, root_name: TestSup, init_module: Supervisor.Default, strategy: :one_for_one, intensity: 3, period: 5, max_children: :infinity, extra_arguments: [], strategy: :one_for_one, distribution_strategy: Horde.UniformDistribution, process_redistribution: :passive, members: [TestSup]], supervisor_ref_to_name: %{#Reference<18568.3730536476.3303276547.200835> => {TestSup, :"loner-cluster3@127.0.0.1"}, #Reference<18568.3730536476.3303276547.200846> => {TestSup, :"loner-cluster4@127.0.0.1"}, #Reference<18568.3730536476.3303276547.200882> => {TestSup, :"loner-cluster2@127.0.0.1"}, #Reference<18568.3730536476.3303276548.200472> => {TestSup, :"loner-cluster1@127.0.0.1"}}, waiting_for_quorum: []}
```

Which is the same line as the previous crash, but a different bad match term.

Modified/simplified test code:

```elixir
defmodule HordeTest do
  use ExUnit.Case

  test "test" do
    nodes = LocalCluster.start_nodes("loner-cluster", 4, files: [__ENV__.file])

    [n1, n2, n3, n4] = nodes

    Enum.each(nodes, &Node.spawn(&1, __MODULE__, :setup_horde, []))

    Process.sleep(1000)

    :rpc.call(n1, __MODULE__, :set_cluster, [nodes])
    {:ok, _pid} = :rpc.call(n1, Horde.DynamicSupervisor, :start_child, [TestSup, TestServer])

    Process.sleep(1000)

    g1 = [n1, n2]
    g2 = [n3, n4]
    Schism.partition(g1)
    Schism.partition(g2)

    :rpc.call(n1, __MODULE__, :set_cluster, [n1, n2])
    :rpc.call(n3, __MODULE__, :set_cluster, [n3, n4])

    Process.sleep(1000)

    Schism.heal(nodes)
    :rpc.call(n1, __MODULE__, :set_cluster, [nodes])

    Process.sleep(1000)

    pids = :rpc.multicall(nodes, Horde.Registry, :whereis_name, [{TestRegistry, TestServer}]) |> elem(0)

    assert Enum.all?(pids, &is_pid/1)
    assert pids |> Enum.uniq() |> length == 1
  end

  def setup_horde do
    {:ok, _} = Application.ensure_all_started(:horde)
    {:ok, _} = Horde.Registry.start_link(name: TestRegistry, keys: :unique, delta_crdt_options: [sync_interval: 50])
    {:ok, _} = Horde.DynamicSupervisor.start_link(name: TestSup, strategy: :one_for_one, delta_crdt_options: [sync_interval: 50])

    receive do
    end
  end

  def set_cluster(nodes) do
    registries = for n <- nodes, do: {TestRegistry, n}
    :ok = Horde.Cluster.set_members(TestRegistry, registries)

    supervisors = for n <- nodes, do: {TestSup, n}
    :ok = Horde.Cluster.set_members(TestSup, supervisors)
  end
end

defmodule TestServer do
  use GenServer, restart: :transient

  def start_link(args) do
    GenServer.start_link(__MODULE__, args, name: {:via, Horde.Registry, {TestRegistry, __MODULE__}})
  end

  def init(_) do
    Process.flag(:trap_exit, true)
    {:ok, nil}
  end

  def handle_info({:EXIT, _, {:name_conflict, _, _, _}}, state) do
    {:stop, :normal, state}
  end
end
```

**Comment by derekkraan** [comment] 2019-12-24 09:47
Hi @bernardd, this looks an awful lot like a bug I killed in #190. It's merged into master already; can I ask you to run these tests again and confirm? If it's not the case then I will investigate further.

**Comment by bernardd** [comment] 2019-12-24 10:03
Will do, thanks. I almost certainly won't get to it until the new year. Have a great christmas or whatever else in the meantime, and thanks for all your hard work 🎄

**Comment by derekkraan** [comment] 2019-12-24 10:04
Thanks @bernardd, merry christmas to you too :santa:.

**Comment by bernardd** [comment] 2020-01-02 00:18
Hi @derekkraan, happy new year.
So the good news is that I'm no longer seeing the `:name_conflict` or `:already_started` crashes with the new code. The down-side, however, is that I'm still seeing cases where the supervised process disappears (the second output block in the original report).

**Comment by derekkraan** [comment] 2020-01-02 08:52
Hi @bernardd ,

Thanks for debugging. It sounds like we are half-way there. I am able to reproduce the case where supervised processes disappear. I'll try to make some time soon to look into this in depth to see what's going on under the hood.

**Comment by derekkraan** [comment] 2020-01-11 13:28
OK, I think I am getting an idea of why this happens. Basically, when a process receives `{:EXIT, {:name_conflict, _}, _, _}`, it causes that process to exit, and this causes Horde to mark it for removal from the cluster. This is _incorrect_ behaviour. Basically, we are _still_ controlling for process uniqueness in two places (Horde.DynamicSupervisor and Horde.Registry). When the process gets removed, it _also_ removes copies of itself from the rest of the cluster, which is definitely _not_ what we want.

One possible solution is to stop deduping processes from Horde.DynamicSupervisor altogether (and actually just `dupe` them when a netsplit occurs, so that the dupes can be cleaned up by Horde.Registry).

I'm not sure how much I like this solution though, since it makes `Horde.DynamicSupervisor` a bit weird, if you don't use it in conjunction with `Horde.Registry`, and you have a netsplit, you will end up with duplicate processes all over your system.

Then again, `Elixir.DynamicSupervisor` also doesn't stop you from creating duplicate processes.

Maybe this is just one of the quirks of a distributed processor: you will end up with duplicate processes in a netsplit unless you are enforcing uniqueness.

Any thoughts @bernardd @pedro-gutierrez? (#191 is related I think)

**Comment by derekkraan** [comment] 2020-01-11 13:32
This might mean that we can stop tracking child_id altogether. `Elixir.DynamicSupervisor` just tracks by pid. In `Horde.DynamicSupervisor`, we create a random child_id to facilitate deduping after a netsplit. If we don't want to do deduping from the supervisor anymore, then we should probably just do as `Elixir.DynamicSupervisor` does and just track pids.

**Comment by bernardd** [comment] 2020-01-20 04:18
I think that's a perfectly reasonable solution. The point of the supervisor is not to enforce uniqueness - that's precisely the job of the registry (or at least one of them), and if people don't use the registry it then they can't really complain when it's functionality doesn't happen :)

**Comment by evan-gordon** [comment] 2020-01-28 22:37
Hi @derekkraan 
We've been using horde for a while now and I've noticed this bug as well and it's been wreaking havok on our systems. Is the fix in master, or is it still being worked on?

As a follow up, what changes would be required in my codebase to facilitate this fix. 

Lastly if this fix isn't merged in yet, what kind of timeline are you currently looking at for this?

Let me know if there is any information you need from me. :)

**Comment by derekkraan** [comment] 2020-01-29 13:13
@evan-gordon this fix is not in master yet. I haven't started working on it and I also can't say when I will. 

If you are using Horde.DynamicSupervisor in combination with Horde.Registry then there should not be any changes required in your codebase to facilitate this fix.

Cheers
Derek

**Comment by evan-gordon** [comment] 2020-01-29 22:48
Hi @derekkraan 

Thanks for the prompt update on this.

I'll see if i can get some time to work on a PR for this in the meantime based off of the discussion above. My schedule is a bit off with everything picking up after the holidays, but ill do what i can :)

**Comment by bernardd** [comment] 2020-01-29 22:58
@evan-gordon Yell out if you do manage to make any progress on it - I was thinking of taking a stab at it myself over the next couple of days if/when I have a moment (though whether I would be able to contribute anything useful is another question entirely :)).

**Comment by evan-gordon** [comment] 2020-01-29 23:45
@bernardd will do! I feel exactly the same though

**Comment by derekkraan** [comment] 2020-02-27 07:18
@bernardd @evan-gordon I have made an attempt to fix this issue. I'm not yet 100% sure it works perfectly, but if you could take a look at #196 an try to break it, that would help a lot.

**Comment by bernardd** [comment] 2020-03-02 01:50
@derekkraan All my tests are passing happily using that branch, I'll keep doing some more testing, buit from my perspective it looks like the issue's sorted. Thanks heaps for your work on it, it's greatly appreciated.

**Closed** 2021-06-04 07:51 UTC
Labels: bug
