### ISSUE TITLE
Issues with timeouts across the cluster

### ISSUE THREAD

**Issue by wittjosiah** [derekkraan/horde#211] opened 2020-09-23 17:57 UTC
Want to start by thanking you for all the work on Horde, I've found it very useful and am continuing to learn things working with it.

Currently we're running [a commit](https://github.com/derekkraan/horde/commit/bcf72fbed4dc8df809cbdf283fc6584ecb088a82) from the master branch prior to the 0.8 release. Running that we regularly see timeouts from GenServer calls within Horde which seem to crash some processes. Interestingly this has not yet seemed to affect anything in practice so the processes seem to reboot fine. The 0.8 release seems to fix these timeouts, I believe because of [this commit](https://github.com/derekkraan/horde/commit/e932f4d387b305e825fb37b88231a9497c6c8254), however following upgrading to 0.8.1 we started to occasionally have different timeout issues which do affect the service in practice.

We started to see [this warning](https://github.com/derekkraan/horde/blob/master/lib/horde/supervisor_telemetry_poller.ex#L36) regularly with the output reason being `{:timeout, {GenServer, :call, [MyApp.GlobalSupervisor, :get_telemetry, 5000]}}`. This in and of itself didn't seem to cause any issues, however after running for a while on 0.8.1 multiple times we've found that calls to the processes being tracked by horde start timing out. I'm not sure if this is related to that warning but they seem similar enough manifestations that they might be. Thus far we haven't been able to find anything that causes this to start happening but redeploying with an older version of Horde fixes the issue and we've never encountered the issue running the commit we currently are. As such we have not been able to upgrade to the latest version of Horde.

Any ideas or help you can provide are appreciated. If there's any other information that I can provide let me know. We are currently running Elixir 1.10.3 on OTP 22.2.7. If we make any headway on this issue I'll be sure update here. Thanks!

**Comment by mjquinlan2000** [comment] 2020-10-05 18:31
I can confirm that I am seeing the same thing with my cluster on 0.8.1 

$ elixir -v
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 22)

erlang 22.3.4.1
elixir 1.10.3

**Comment by AttilaGal** [comment] 2020-10-07 07:22
I'm having similar issues. Our setup reads from a RabbitMQ queue, that hands of messages to processes that are managed by Horde. When the queue gets clogged up with a backlog of messages, Horde v0.8.1 seems to freeze up after a short while without logging anything. I do see some other issues with DB performance that may trigger some timeouts/crashes in my processors, but Horde v0.7.1 has no issues with this.

elixir --version
Erlang/OTP 22 [erts-10.5.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.7.4 (compiled with Erlang/OTP 20)

**Comment by mjquinlan2000** [comment] 2020-10-07 14:36
@AttilaGal it's interesting that you mention that. I also have a similar setup in which a RabbitMQ cluster hands off messages to horde processes. It did actually expose some issues with my distributed processes that I am thankful for. I have since fixed these issues and it seems like the cluster is running smoothly. However, it appears that any locking up of processes causes Horde to become unresponsive across the cluster.

**Comment by derekkraan** [comment] 2020-10-07 14:45
Hi folks,

Just to eliminate one potential source of issues: are you using `handle_continue/2` callbacks in the processes you are starting with Horde? A supervisor (Horde, or any of the standard OTP supervisors) blocks on the `init/1` callback of its child processes.

If that's not it, could you give me some more information related to your application? Eg, how many nodes are in the cluster? how many processes are you supervising with Horde? are you doing anything specific when it locks up (deploying for example)?

Derek

**Comment by mjquinlan2000** [comment] 2020-10-07 14:54
I am using `handle_continue/2' callbacks in my horde processes. My init looks like:

```
  @impl GenServer
  def init(id) do
    {:ok, {id, %{}}, {:continue, :initialize}}
  end
```

and using `handle_continue/2` for many other things. Would this only present a problem with the `init/1` callback or can I not use `handle_continue/2` anywhere?

**Comment by derekkraan** [comment] 2020-10-07 14:55
No, this is good. I meant "please ensure you're using `handle_continue/2` as applicable to ensure that the supervisor doesn't block unnecessarily waiting for your `init/1` to return".

**Comment by mjquinlan2000** [comment] 2020-10-07 14:57
Ok. Thank you for the clarification. None of my horde processes are doing any actual work within the `init/1` call. All of them continue to an initialization function.

**Comment by mjquinlan2000** [comment] 2020-10-07 15:05
it also appears that when I kick my horizontal pod autoscaler (I'm using Kubernetes w/ libcluster) to cycle some pods to see how horde responds, I'm getting a lot of these errors

```
15:00:56.652  [error] GenServer MyApp.Observer.RequesterSupervisor.NodeListener terminating
** (stop) exited in: GenServer.call(MyApp.Observer.RequesterSupervisor, {:set_members, [{MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-5-167.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-7-113.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-1-73.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-5-168.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-7-114.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-6-87.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-5-169.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-0-154.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-7-116.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-7-115.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-1-74.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-0-155.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-5-172.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-6-89.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-5-170.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-5-171.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-7-117.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp@10-56-6-90.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp_maint_@10-56-6-89.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp_maint_@10-56-0-156.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp_maint_@10-56-6-90.default.pod.cluster.local"}, {MyApp.Observer.RequesterSupervisor, :"MyApp_maint_@10-56-7-117.default.pod.cluster.local"}]}, 5000)
    ** (EXIT) time out
    (elixir 1.10.3) lib/gen_server.ex:1023: GenServer.call/3
    (horde 0.8.0) lib/horde/node_listener.ex:50: Horde.NodeListener.set_members/1
    (horde 0.8.0) lib/horde/node_listener.ex:39: Horde.NodeListener.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:nodedown, :"MyApp@10-56-0-156.default.pod.cluster.local", [node_type: :visible]}```

**Comment by derekkraan** [comment] 2020-10-07 15:07
Ok. how many nodes in your cluster? How many processes under supervision by Horde?

**Comment by mjquinlan2000** [comment] 2020-10-07 15:42
My HPA is set up to run anywhere from 1 - 19 erlang nodes depending on the demand. I'm seeing this issue when I bring down one erlang node regardless of the number of nodes currently running. The number of running processes can be anywhere from 0 to hundreds depending on the activity on the nodes. However, this is a staging environment so the activity is pretty low. If the processes are not called upon for 60 seconds, they shut down.

I actually think this is related to my PreStop hooks for the pod lifecycle. I'm not actually gracefully shutting down the nodes so the second stacktrace I posted may be unrelated. I will post an update when I get another release out with PreStop hooks set correctly.

**Comment by AttilaGal** [comment] 2020-10-07 17:19
Hi again. I'm not using handle_continue yet, and there are some DB calls happening during init which may have lead to timeouts (did some optimizations today). However, when I reverted back to Horde v0.7.1 this didn't seem to be an issue. I've only tried it on our development servers which have only 1 node.

**Comment by wittjosiah** [comment] 2020-10-07 17:29
We're also not using `handle_continue` at the moment and have a db call happening during the init. It's not a heavy query but it is there. Going try to find the time soon to do an experiment offloading the initialization to `handle_continue` and see if that helps at all.

**Comment by mjquinlan2000** [comment] 2020-10-07 19:50
After further investigation, I was not stopping the erlang nodes gracefully. You can ignore the comment about the `call :set_members` timeout.

**Comment by wittjosiah** [comment] 2020-10-09 16:53
I've discovered a couple more things playing around with this over the last couple days. I added in a `handle_continue` to the `init` of our `GenServer` which is being supervised by Horde and that seems to be working well with 0.8.1. I am however still seeing those "Exit while fetching metrics" warnings at points. So far I've noticed two cases where this occurs:
1. The first case is just random timeouts that happen once or twice and then stop, I suspect this is somewhat normal and not anything to be too worried about. Over the past 36 hours I noticed 3-4 of those on a two node cluster.
2. The second case is more worrying and I think where problems start to happen. After doing a deployment the warnings seem to start happening regularly and don't stop. I'm now wondering if this has something to do with the way nodes are joining/leaving the cluster.

Does this second case sound like it could be the case or at least part of the problem? What are the steps that should be taken for nodes leaving the cluster?

To add a bit more details about how we're setup currently, each node we have is a docker container in ECS and we're using DNS with libcluster to cluster them together.

**Comment by derekkraan** [comment] 2020-11-02 10:34
Can you all upgrade to 0.8.3 and re-open if this issue persists? I strongly suspect it has been fixed by #218.

**Closed by derekkraan** 2020-11-02 10:34 UTC
Labels: bug

**Comment by wittjosiah** [comment] 2020-11-10 13:34
I can confirm that we've been able to upgrade to 0.8.3 in production without the massive slew of warnings and subsequent slew of timeout errors. We still experience some occasional timeout problems but its unclear if it is a Horde issue or not and are likely not the same as this issue. If we determine the problem to be Horde there I will open a separate issue, I agree that this is likely resolved now.

**Comment by mszmurlo** [comment] 2021-03-13 06:45
Hi,

I actually ran in the a similar issue with Horde 0.8.3. The demonstrator is on [Gitlab](https://gitlab.com/mszmurlo/poc/-/tree/timeouts_when_reentrance_of_Horde.DynamicSupervisor.start_child_211).

The short description is that  a call to `Horde.DynamicSupervisor.start_child()` from a function that was previously called by `Horde.DynamicSupervisor.start_child()` from another module freezes the node.

More in details, the demonstrator actually mimics an API backend accessible by HTTP with JSON payload. A connected user is managed by a `UA`, a user agent implemented as a `GenServer`. Each active connection of the actual user (from web, mobile, tablet, ...) is managed by a `CA`, a connection agent also implemented as a `GenServer`. There might be many `CA` for one `UA`. Each `UA` and `CA` is registered in horde's registry with unique keys `caid` and `uaid`. The login procedure (credentials removed for simplicity) is as follows:

1. When the HTTP requests arrives to the login controller, the controller calls Horde.DynamicSupervisor.start_child(POC.DSup, {POC.CA, {uaid, caid}})
2. CA.start_link() gets called. It calls GenServer.start_link() which in turn calls CA.init()
3. In CA.init(), we are supposed to create a new UA if it's the first connection for that user, or, if the user is already connected with another CA, to 'register' the CA with that UA. Hence, CA.init() calls Horde.DynamicSupervisor.start_child(POC.DSup, {POC.UA, {uaid, caid}})
4. Whatever is supposed to happen later, at that very moment the node freezes and I get the following logs forever:

```
(1) [info] POST /api
      [debug] Processing with POCWeb.Login.exec/2
        Parameters: %{"cmd" => "login"}
        Pipelines: [:api]
(2) [debug] Login.exec()
(3) [debug] CA.start_link({uaid="AIHUPRDTPM", caid="LQNIUWRDSQ")
(4) [debug] CA.init(uaid="AIHUPRDTPM", caid="LQNIUWRDSQ")
(5) [warn] Exit while fetching metrics from POC.DSup.
      Skip poll action. Reason: {:timeout, {GenServer, :call, [POC.DSup, :get_telemetry, 5000]}}.
      [warn] Exit while fetching metrics from POC.DSup.
      Skip poll action. Reason: {:timeout, {GenServer, :call, [POC.DSup, :get_telemetry, 5000]}}.
```
1. Reception of the HTTP request
2. In the login controller just before calling `Horde.DynamicSupervisor.start_child()` the first time
3. In `CA.start_link()` just before calling `GenServer.start_link()`
4. In `CA.init()` just before calling `Horde.DynamicSupervisor.start_child()` the second time to create the `UA`.
5. *The warning of the death*

I also tried to downgrade Horde to version 0.7.1 as similar issues were reported here up to version 0.8.2. I still got a freeze but this time I get the following error:
```
iex(1)> [info] POST /api
[debug] Processing with POCWeb.Login.exec/2
  Parameters: %{"cmd" => "login"}
  Pipelines: [:api]
[debug] Login.exec()
[debug] CA.start_link({uaid="OEZMYWTTAY", caid="AHNWWUTYSJ")
[debug] CA.init(uaid="OEZMYWTTAY", caid="AHNWWUTYSJ")
[error] Error when calling MFA defined by measurement: Horde.DynamicSupervisorTelemetryPoller :poll [POC.DSup] 
Class=:exit
Reason={:timeout, {GenServer, :call, [POC.DSup, :get_telemetry, 5000]}}
Stacktrace=[
  {GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 1023]}, 
  {Horde.DynamicSupervisorTelemetryPoller, :poll, 1, [file: 'lib/horde/supervisor_telemetry_poller.ex', line: 27]}, 
  {:telemetry_poller, :make_measurement, 1, [file: '/home/maurycy/dev/alaaarm/poc/deps/telemetry_poller/src/telemetry_poller.erl', line: 308]}, 
  {:telemetry_poller, :"-make_measurements_and_filter_misbehaving/1-lc$^0/1-0-", 1, [file: '/home/maurycy/dev/alaaarm/poc/deps/telemetry_poller/src/telemetry_poller.erl', line: 304]}, 
  {:telemetry_poller, :"-make_measurements_and_filter_misbehaving/1-lc$^0/1-0-", 1, [file: '/home/maurycy/dev/alaaarm/poc/deps/telemetry_poller/src/telemetry_poller.erl', line: 304]}, 
  {:telemetry_poller, :handle_info, 2, [file: '/home/maurycy/dev/alaaarm/poc/deps/telemetry_poller/src/telemetry_poller.erl', line: 326]}, 
  {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, 
  {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}, 
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
]
```

I'm king of completely stuck so any hint would be helphul

**Comment by derekkraan** [comment] 2021-03-13 08:30
@mszmurlo what you're experiencing is a deadlock, and has nothing to do with Horde. My advice is to make a second Horde.DynamicSupervisor, or, move the second call to start_child out of the init/1 callback (handle_continue?)

**Comment by mszmurlo** [comment] 2021-03-14 07:08
@derekkraan : Thanks for your time; thanks for your reply and advice. I created 2 supervisors and `CA` and `UA` processes get created properly.

Thanks for the support and for all the work done on Horde

**Comment by puneetloya** [comment] 2021-05-06 19:40
> My HPA is set up to run anywhere from 1 - 19 erlang nodes depending on the demand. I'm seeing this issue when I bring down one erlang node regardless of the number of nodes currently running. The number of running processes can be anywhere from 0 to hundreds depending on the activity on the nodes. However, this is a staging environment so the activity is pretty low. If the processes are not called upon for 60 seconds, they shut down.
> 
> I actually think this is related to my PreStop hooks for the pod lifecycle. I'm not actually gracefully shutting down the nodes so the second stacktrace I posted may be unrelated. I will post an update when I get another release out with PreStop hooks set correctly.

@mjquinlan2000 How are you implementing graceful shutdown? what do you use for preStop hook?

**Comment by hubertlepicki** [comment] 2023-06-01 07:42
Not sure if this is useful, but I am observing a similar thing happening from time to time, when starting processes under Horde.DynamicSupervisor.

These proceese are *not* using handle_continue during initialization, they do things the old fashioned way by scheduling a message to be sent to themselves. The relevant code is:

```elixir
  def init(account_id) do                                                                                                                                                               
    Logger.metadata(account_id: account_id)                                                                                                                                             
                                                                                                                                                                                        
    state = %{account_id: account_id, poll_timer_ref: nil, check_timer_ref: nil}                                                                                                        
                                                                                                                                                                                        
    {:ok, state |> schedule_poll(@min_initial_poll_delay + jitter())}                                                                                                                   
  end
  
   defp schedule_poll(state, delay \\ @work_interval) do                                                                                                                               
      Logger.info("[#{__MODULE__}] scheduling poll in #{delay}ms")                                                                                                                      
                                                                                                                                                                                        
      state                                                                                                                                                                             
      |> cancel_timer(:poll_timer_ref)                                                                                                                                                  
      |> Map.replace(:poll_timer_ref, Process.send_after(self(), :poll, delay))                                                                                                         
    end  
 
   defp cancel_timer(state, key) do                                                                                                                                                      
     case state[key] do                                                                                                                                                                  
      nil ->                                                                                                                                                                            
        state                                                                                                                                                                           
                                                                                                                                                                                        
      timer_ref ->                                                                                                                                                                      
        Process.cancel_timer(timer_ref)                                                                                                                                                                                                                                                                                                                                    
        state                                                                                                                                                                           
        |> Map.replace(key, nil)                                                                                                                                                        
    end                                                                                                                                                                                 
  end
   
  @jitter_range 5 * 60 * 1000                                                                                                                                                           
  defp jitter(), do: :rand.uniform(@jitter_range)
```

Not sure what could go wrong in this code that'd result in a deadlock, honestly don't see anything except calls to Logger and Process and I don't think none of them should hang...
