### ISSUE TITLE
Intermittent errors in horde that seems to run fine otherwise. 

### ISSUE THREAD

**Issue by Ivor** [derekkraan/horde#69] opened 2019-01-31 16:17 UTC
Hi Derek. 

We're continuing our process of getting to production with a live horde cluster. I am excited as always.

We were testing our cluster (I work remotely, but the guys in the office tried it out) and while the cluster seems to do what is expected, they did notice some errors appearing in the logs. 

```
(stop) exited in: GenServer.call(MyApp.HordeSupervisor, :members, 5000)
(EXIT) time out
(elixir) lib/gen_server.ex:989: GenServer.call/3
(hive) lib/my_app/horde/cluster.ex:99: MyApp.HordeCluster.members/0
(hive) lib/my_app/horde/cluster.ex:71: anonymous fn/0 in MyApp.HordeCluster.start_horde_children/0
(elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<1.74019401/0 in MyApp.HordeCluster.start_horde_children/0>
Args: []```
```

This error comes from a line that is called with: 

```
{:ok, members} = Horde.Cluster.members(MyApp.HordeSupervisor)
```

We start our cluster with the following children: 

```
      {Horde.Supervisor,  name: MyApp.HordeSupervisor,
                        strategy: :one_for_one,
                        distribution_strategy: strategy(),
                        children: []},
      {Horde.Registry, name: MyApp.HordeRegistry, keys: :unique},
      {MyApp.Horde.NodeMonitor, name: MyApp.Horde.NodeMonitor}
```

Do you have any idea what might be causing this? It doesn't seem to have a detrimental effect on the functioning of the cluster. 

The other issues they discovered were: 

```
GenServer Hive.HordeRegistry terminating

(FunctionClauseError) no function clause matching in Horde.RegistryImpl.handle_cast/2
(horde) lib/horde/registry_impl.ex:91: Horde.RegistryImpl.handle_cast({:request_to_join_hordes, {:registry, "Jw9eSu4x4E4N5B8f87h2YA==", #PID<30324.493.0>, false, {#PID<30324.447.0>, #Reference<30324.165341209.964952065.63890>}
}}, %Horde.RegistryImpl.State

{keys_ets_table: :"keys_Elixir.MyApp.HordeRegistry", keys_pid: #PID<0.1540.0>, members_pid: #PID<0.1532.0>, node_id: "Coxg9YdgjfgDRewOBedkrw==", nodes: [:"4000@192.168.0.61", :"4001@192.168.0.61"], pids_ets_table: :"pids_Elixir.MyApp.HordeRegistry", processes_updated_at: 0, processes_updated_counter: 0, registry_ets_table: MyApp.HordeRegistry, registry_pid: #PID<0.1536.0>}
```

and

```
GenServer Hive.HordeSupervisor.Registry terminating

(FunctionClauseError) no function clause matching in anonymous fn/1 in Horde.SupervisorImpl.monitor_supervisors/2
```

I am hoping that either these are known to you and not something to worry about, or that it might help you. If you recognise any of these as legitimate issues with our implementation, please let me know. 

Thanks for the great project!

**Comment by derekkraan** [comment] 2019-02-01 08:55
Hi @Ivor,

The first error is odd, because the `handle_call` for `:members` only returns the members from the state of the GenServer. So if this is timing out then that indicates that the supervisor was busy doing something else for that time (terminating a process maybe?)

The second error, (`:request_to_join_hordes`) is really very strange. I don't see anywhere in the codebase where this could occur (there is an extra `false` in the tuple).

The third error, it seems like the `members` state doesn't match the expected shape `{node_id, %{pid: pid}}`. I don't know why this could be though, I've just reviewed the code and we only add `[node_id, node_info(state)]` to the members crdt.

What versions of horde and delta_crdt are you running?

**Comment by Ivor** [comment] 2019-02-01 09:39
Hi Derek. 

The version we are running are (from our mix.lock file): 

```
"delta_crdt": {:hex, :delta_crdt, "0.3.1", "a50bff0460da2d9b0559a68c0116bf8f0c3847de272bdce4a391aae2063902d3", [:mix], [], "hexpm"},
"horde": {:git, "https://github.com/derekkraan/horde.git", "5cb07da15f5b9acba2d92a610309c0a52d0d9c37", []}
```

I think while my colleagues were testing this they would intermittently kill a node or one of them would kill their wifi to simulate a network partition. Perhaps the first error was as a result of that? 

I'll have to investigate further. S=Do you have pointers for where to start to investigate any of these issues?

**Comment by derekkraan** [comment] 2019-02-01 09:52
`:request_to_join_hordes` is always coming from your own code somewhere, so you should be able to find a timeout error on that call somewhere in your logs to assist you in tracing the call from start to end.

To fix the first issue I'm considering that the call to `members/1` should have a timeout of `:infinity`.

And for the last one, that's a real head-scratcher. You could try the latest `master` of delta_crdt to see if you can reproduce it. That should improve the overall performance as well.

**Comment by Ivor** [comment] 2019-02-01 09:55
Thank you very much! I will investigate after the weekend. My head is fried after this week :)

**Comment by derekkraan** [comment] 2019-02-27 14:53
Hi @ivor, if you have time, could you test version 0.5.0-rc.1 to see if this bug has been fixed?

**Comment by derekkraan** [comment] 2019-04-16 06:10
I'm closing this issue for now since Horde has been overhauled quite a bit since this was opened. Feel free to re-open (or open a new issue) if you see this again with 0.5.0-rc.12 or higher!

**Closed by derekkraan** 2019-04-16 06:10 UTC

**Comment by Ivor** [comment] 2019-04-16 06:50
Hi Derek. Thank you :) Horde is very much appreciated. I'm pretty swamped at the moment, but will probably need to do some work on the Horde related part of our system in a few weeks. Will have a look then! 

Good luck!
